# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3879bae1ee7b939b8fecb0717b3336328a69326149bfa92b7e0c2d511988f19b7befc17a4b2609701e8149a38da3a1ebeedf8a02812f4144614098f4a21a01

test:
  secret_key_base: b42efb3e02bf9e0fff6d09c433b1dbb265d8704bbdbf877701bcdd31a4c44bcc54fdc22fcb0b0a7d0f274d19a337b97e7c4c36602baf3ac5ba7764d203565cd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
